### ISSUE TITLE
`editor-libcosmic` example crashes on changing font size

### ISSUE THREAD

**Issue by ales-tsurko** [pop-os/cosmic-text#105]
I'm on macOS 13.2.1, with M1. When I run the example and open `sample/hello.txt` and trying to change the font size to *Title 4* the application panics with:

```
thread 'main' panicked at 'attempt to subtract with overflow', src/shape.rs:711:37
```

The issue appears only on debug build.

**Comment by nicoburns** [comment]
I think this is fixed by https://github.com/pop-os/cosmic-text/pull/98

**Comment by geieredgar** [comment]
#98 was superseded by #108, which is already merged, so the example shouldn't crash anymore.
