### ISSUE TITLE
96.8MB memory usage in rich-text example

### ISSUE THREAD

**Issue by i509VCB** [pop-os/cosmic-text#107]
Originally I found this issue in the advanced text branch for iced. My system reports that 96.8MB is used when running. It seems like a bit much to use that much memory for just displaying some text. Iced gave memory usage of around 100MB for the checkbox example on the advanced-text branch.

I ran dhat from valgrind for iced and it seems that some parts of rustybuzz appears to be the cause of 12MB of memory usage.

I am running on Linux on aarch64.

**Comment by jackpot51** [comment]
#97 may fix this, can yoi check? I'd bet most of the memory usage is from memory maps.

**Comment by i509VCB** [comment]
#97 did not reduce the memory usage.

**Comment by i509VCB** [comment]
Some more low resolution testing, it seems that memory usage goes from 40MB to 96MB after the first call to `Editor::shape_as_needed`.

**Comment by geieredgar** [comment]
Could you try #97 again? I've added a commit that reduces the calls to `get_font` (or more precisely, only calls `get_font` when really necessary). This reduced the memory usage on my system. I will look into a way to discard fonts that aren't used anymore.

**Comment by geieredgar** [comment]
I've also opened a new PR #109 to allow users to discard unused fonts explicitly.

**Comment by i509VCB** [comment]
The new commit on #97 makes a nice improvement, 37MB now which is about what creating a window seems to do on my system.
