### ISSUE TITLE
example editor-libcosmic light mode is black on almost-black

### ISSUE THREAD

**Issue by WhyNotHugo** [pop-os/cosmic-text#112]
Running the editor-libcosmic example, I get this:

![image](https://user-images.githubusercontent.com/730811/227581077-f4ecfca7-1ae4-4403-a1f8-b756e83c87e4.png)

I think it's rendering black on almost-black. Dark mode is fine though:

![image](https://user-images.githubusercontent.com/730811/227581236-88e44ac6-d172-4ec0-b836-12258e269653.png)

**Comment by Aargonian** [comment]
Can confirm that I get the same issue, running on macOS Ventura 13.3.1. 

I'm attempting to follow the small example on the main documentation page for the project: https://docs.rs/cosmic-text/latest/cosmic_text/

For some reason, the foreground and the background of the text appear to be getting rendered at or near the same color as one another:

![image](https://github.com/pop-os/cosmic-text/assets/8229879/b6193f82-4a59-4f58-8666-f5f406fc1986)

I use the following relatively simple program to create the problem above, for a toy project I'm working on:
```Rust
use cosmic_text::{Attrs, Buffer, FontSystem, Metrics, SwashCache};
use ember_ui::*;

fn main() {
    let _options = WindowOptions {
        ..WindowOptions::default()
    };

    let mut renderer = SoftwareRenderer::new(640, 480);
    let mut window = Window::new("Hello, World!", 640, 480).expect("Failure to make window.");

    // Font Stuff
    let mut font_system = FontSystem::new();
    let mut swash_cache = SwashCache::new();
    let metrics = Metrics::new(14.0, 20.0);
    let mut buffer = Buffer::new(&mut font_system, metrics);
    let mut buffer = buffer.borrow_with(&mut font_system);
    buffer.set_size(85.0, 25.0);
    let attrs = Attrs::new();
    buffer.set_text("Hello, Rust! 🦀\n", attrs);
    buffer.shape_until_scroll();
    for run in buffer.layout_runs() {
        for glyph in run.glyphs.iter() {
            println!("{:#?}", glyph);
        }
    }

    let text_color = cosmic_text::Color::rgb(0xFF, 0x00, 0x00);

    let rx = 10;
    let ry = 10;

    renderer.clear(ember_ui::Color::from(0xFFFFFFFF));

    // Draw Text
    buffer.draw(&mut swash_cache, text_color, |x, y, w, h, color| {
        let x = x + rx;
        let y = y + ry;
        let c = Color {
            a: 0xFF,
            r: color.r(),
            g: color.g(),
            b: color.b(),
        };
        renderer.draw_rect(x as u32, y as u32, w, h, c);
    });

    renderer.flip();

    loop {
        window.update(&renderer);
    }
}
```

I can reproduce the above Issue with the editor-libcosmic example. Interestingly, I can comment out all the following lines in the text_box.rs file, except for creating the pixel_buffer, and everything renders perfectly fine (minus text of course).

https://github.com/pop-os/cosmic-text/blob/bfb5eefbfa869915e47824877af68a5307cf301c/examples/editor-libcosmic/src/text_box.rs#L240-L253

**Comment by 0HyperCube** [comment]
The background is determined by `syntect::highlighting::ThemeSet` @Aargonian. We could update the theme to something like "base16-ocean.light" for light mode and keep the existing "base16-eighties.dark" for dark mode.
