### ISSUE TITLE
Better rendering API

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-text#12]
Having the glyph cache inside of cosmic-text wastes memory if the image will be immediately uploaded to GPU, and the API returning pixel positions and colors instead of images decreases performance.

**Comment by i509VCB** [comment]
Is the rendering api something which could output effectively a description of draw calls or are images the only reasonable way to do this?

**Comment by genusistimelord** [comment]
this one is a bit harder as you really don't want to support the renderer internally but setup ways to do the text layout and still allow the end user to build their Atlas etc for rendering. not really sure how to go about this easily myself. Maybe might require a trait API that can be called upon within the Layout draw. like cache check, Cache insert, and cache ID so when creating the vertices later it could build the proper locations?  Could also use the Trait API with the current Cache method too.

**Comment by jackpot51** [comment]
Improved a bit, now swash is optional and the glyphs can be inspected directly
