### ISSUE TITLE
Upgrade to fontdb 0.14

### ISSUE THREAD

**Issue by notgull** [pop-os/cosmic-text#125]
`fontdb` version 0.14 contains a breaking change that allows one to get the IDs from a font that was just registered, which helps when it comes to implementing a "load font family" function. It would be nice to bump the version of this crate. Since this would be a breaking change, I understand if it's not high priority; it should probably be bundled with another breaking change once the time comes.

**Comment by tigregalis** [comment]
I would like this too. There are a couple ways around it but none of them are satisfying, and now they're no longer needed.
