### ISSUE TITLE
Constrained buffer with unconstrained buffer's width does not produce the same result

### ISSUE THREAD

**Issue by tigregalis** [pop-os/cosmic-text#134]
Reproduction: https://github.com/tigregalis/cosmic-text-width-constraint-bug

![out-expected.png](https://github.com/tigregalis/cosmic-text-width-constraint-bug/raw/main/out-expected.png)

When we draw text in Bevy, we currently do 2+ "size" passes (1+ node measurement pass during layout, and 1 rendering pass); the calculated width from the first pass determines the size of the node.

A rare bug(?) occurs when laying out the text `(6)  SomewhatBoringDisplayTransform` with a font size of `18.0` pixels and the font `FiraMono-Medium.ttf`. This shows up in a specific Bevy example, and I haven't been able to reproduce it with other text / font sizes / fonts, but the possibility exists.

We lay out this text in a buffer (`buffer1`) with an `UNBOUNDED` size; the buffer has one line (one layout run) with a certain `width1` (`run.line_w`).

Later, we lay out the same line in a buffer (`buffer2`) with a maximum size of `width1` pixels wide.

That is, the first buffer's width determines the width constraint of the second buffer. I expected that they would produce the same result.

However, this second buffer (`buffer2`) is not considered wide enough to fit that text, so the second word breaks onto a second line.

Even `ceil`ing the width still causes it to break. However, `ceil`ing it and adding some small value (e.g. `0.001`) gets around this behaviour.

**Comment by jackpot51** [comment]
@tigregalis please check if this is fixed now

**Comment by tigregalis** [comment]
Looks good to me.
