### ISSUE TITLE
`Wrap::Word` inserts newline for trailing space (after word)

### ISSUE THREAD

**Issue by grovesNL** [pop-os/cosmic-text#155]
If we have text like `Testing Spacing` in the rich-text example, you can see that the space causes a full empty line to be inserted (tested with the rich-text example):

![image](https://github.com/pop-os/cosmic-text/assets/2113872/bc15a528-95e8-4029-a577-a9c9862e7a1f)

(the cursor also does an interesting thing in this situation)

The behavior seems to have changed in #78. Before #78 this would look like:

![image](https://github.com/pop-os/cosmic-text/assets/2113872/af108087-b9bd-4d79-bf14-ee531d2eea33)

The previous behavior seems better for display, because I wouldn't expect a space to wrap a whole line. Instead I'd expect the space to kind of bind to the word before it, so that "Testing " remains on the first line.

If the old behavior is preferred, I'll try to submit a PR to change how we wrap in this case.

The current handling for word wrapping is located in https://github.com/pop-os/cosmic-text/blob/aa1b37aede5435067bc51667797f16ffb8b8be7d/src/shape.rs#L831-L873 and https://github.com/pop-os/cosmic-text/blob/aa1b37aede5435067bc51667797f16ffb8b8be7d/src/shape.rs#L923-L968

**Comment by Imberflur** [comment]
I've noticed that trailing spaces also affect centered and right aligned text.
