### ISSUE TITLE
unable to find fonts on NixOS

### ISSUE THREAD

**Issue by urlordjames** [pop-os/cosmic-text#167]
# description
`FontSystem::new()` fails to find any fonts on NixOS.

# reproduction
```rust
fn main() {
  pretty_env_logger::init();
  cosmic_text::FontSystem::new();
}
```
output from `RUST_LOG=trace cargo run`:
```
 DEBUG cosmic_text::font::system::std > Locale: en-US
 INFO  cosmic_text::font::system::std > Parsed 0 font faces in 0ms
```

# suggested resolution
Enabling the `fontconfig` feature of `fontdb` seems to resolve the issue.

output with `fontconfig` feature enabled:
```
 DEBUG cosmic_text::font::system::std > Locale: en-US
 INFO  cosmic_text::font::system::std > Parsed 82 font faces in 18ms.
```

**Comment by jalil-salame** [comment]
Running the tests on NixOS fails with `thread 'main' panicked at 'no default font found', src/shape.rs:174:33`:

`test src/lib.rs - (line 14) ... FAILED`
