### ISSUE TITLE
Improve clean debug build speeds 25% by changing `unicode-linebreak` to `xi-unicode`

### ISSUE THREAD

**Issue by kettle11** [pop-os/cosmic-text#2]
Hi! I'm quite excited for this library. 

I'm a big fan of super lean build times so I try to audit dependencies to find areas to improve. In this case it seems `unicode-linebreak` implements a rather chunky `build.rs` script that makes it your second slowest building dependency (after `swash`).

`xi-unicode` pre-bakes the unicode tables without a build.rs so it builds much faster. 

Swapping is an easy one-line change: 

Change this line:

https://github.com/pop-os/cosmic-text/blob/ac83f5846bea89e8f84810ce9e216d223dcc0830/src/font/matches.rs#L246

to this:
```rust
for (end_lb, _) in xi_unicode::LineBreakIterator::new(span) {
```

Alongside the obvious `cargo.toml` changes.

**Edit**: I ran `editor-test` and it reported "All lines matched!". I haven't ran further tests.

**Comment by jackpot51** [comment]
Thanks, I will look into this, would you want to make a PR?

**Comment by jackpot51** [comment]
Merged!
