### ISSUE TITLE
Non-default weights break emojis

### ISSUE THREAD

**Issue by CryZe** [pop-os/cosmic-text#23]
It seems like the font selection might be fairly strict, so because there's no bold version of Emojis it can't find any font and falls back to the Tofu instead.

![image](https://user-images.githubusercontent.com/1451630/198213563-8175c939-e005-4f25-997b-f2f3a51867ff.png)

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/cosmic-text/commit/40175aac109a9d1034865d1452384bb71a16b6de, thanks for reporting!
