### ISSUE TITLE
Bug: tabs being rendered as oval symbols in cosmic-edit

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-text#248]
A good example file is https://github.com/pop-os/alsa-ucm-conf/blob/master_jammy/ucm2/ucm.conf

Indentation with spaces instead of tabs is rendering as expected.

![screenshot-2024-04-26-19-35-15](https://github.com/pop-os/cosmic-text/assets/13512097/118e6b08-b456-44e9-8af4-f502c3f89378)

**Comment by jackpot51** [comment]
@leviport which font is this? Can you test with the latest cosmic-edit?

**Comment by leviport** [comment]
Looks like Fira Mono, and I'm still seeing it on the most current version

![screenshot-2024-06-10-15-37-05](https://github.com/pop-os/cosmic-text/assets/13512097/fde2ec06-0bdc-4c75-be74-72731d671e95)

**Comment by jackpot51** [comment]
Wait for c2f49c8422a9bc67ee75aa742dcd866278299ced to build, it has cosmic-text changes to handle tabs.

**Comment by jackpot51** [comment]
It should be available from master staging now.

**Comment by jackpot51** [comment]
Here is the same file you had open:

![screenshot-2024-06-10-16-28-14](https://github.com/pop-os/cosmic-text/assets/7741236/dd5263d5-91fd-462a-b1be-dc9d5a0a758d)

**Comment by leviport** [comment]
Tabs now appear to be the correct width, but I'm still seeing circles. This is my main work install though, so it could be in a weird state. Let me also check on a fresh setup, just in case.

![screenshot-2024-06-10-17-31-40](https://github.com/pop-os/cosmic-text/assets/13512097/130413b2-c7ae-4efd-b02d-4b8fcb8f8e03)

**Comment by jackpot51** [comment]
I might make the tabs be shaped as spaces to prevent this. I will let you know when it is done

**Comment by jackpot51** [comment]
cosmic-edit is now updated with the fix for this.
