### ISSUE TITLE
Vector path output

### ISSUE THREAD

**Issue by i509VCB** [pop-os/cosmic-text#26]
It would be useful to have a way to output vector paths as an alternative to rendering pixels to an image.

**Comment by Plecra** [comment]
The docs are a bit too sparse for me to tell, so I hope this question is alright :) Is the `draw` function the only output method at the moment? + is the intention that it's used to draw pixels to an output texture?

**Comment by dhardy** [comment]
I think theoretically you could use `BufferLine::layout` with your own texture atlas / glyph caching solution.

**Comment by Plecra** [comment]
I see, thanks! I understand a bit more now. So `swash` is giving us textures for each glyph, which `draw` then enumerates. 

Would it be reasonable to experiment with putting a texture atlas on the GPU and rendering the glyphs as individual quads, in the hope that it could offload some cpu work?

**Comment by dhardy** [comment]
If I ever get around to integrating cosmic-text with KAS this would be my approach — [see here](https://github.com/kas-gui/kas/blob/master/crates/kas-wgpu/src/draw/text_pipe.rs) (essentially this is already implemented over kas-text which has a slightly different [cache key](https://docs.rs/kas-text/latest/kas_text/raster/struct.SpriteDescriptor.html)).
