### ISSUE TITLE
More options to set syntax highlighting for content

### ISSUE THREAD

**Issue by elevenhsoft** [pop-os/cosmic-text#270]
Hi,

Currently we can get syntax highlighting by loading text from file. The syntax is recognized by syntect itself. 
Can we somehow pass a content to buffer by hand instead of loading a file and set syntax to desired extension?

**Comment by jackpot51** [comment]
There is no mechanism for this yet, but it could be added.

**Comment by elevenhsoft** [comment]
Would be awesome to see this option. Syntect comes with some handy methods for this purpose. Do you planning to add this soon or later? :sweat_smile:

**Comment by jackpot51** [comment]
If you want it sooner, you could look at the syntect editor source. The load_text function is pretty simple so you could make a new function that lets you set what you want.

**Comment by elevenhsoft** [comment]
Yeah, that's probably what I will do in this case. Thank you :)
