### ISSUE TITLE
Adds spaces to start of current line when switching with alt-tab

### ISSUE THREAD

**Issue by bartv42** [pop-os/cosmic-text#274]
This happens when using the editor under the regular pop version, not in Cosmic:  When switching back to the editor using alt-tab, spaces get added to either the current line, or to all the currently selected lines:

![image](https://github.com/pop-os/cosmic-text/assets/6816469/5abf2185-5184-450b-9ee7-f0e1699ef4cf)

**Comment by nicoburns** [comment]
Hmm... that sounds like the editor wrapping cosmic-text not dispatching the keypresses correctly rather than an bug in cosmic-text.

**Comment by bartv42** [comment]
I checked again today and this no longer happens.
