### ISSUE TITLE
line_y < 0.0 in LayoutRunIter for certain fonts

### ISSUE THREAD

**Issue by maxmelander** [pop-os/cosmic-text#281]
Hello!

I've noticed that for certain fonts, the calculated `line_y` in `LayoutRunIter::next` can be less than 0.0. This causes the inner while loop to `continue` and you never get back a layout run, even if the buffer does contain valid layout lines.

One example of a font where this happens is the Google Font ["Borel"](https://fonts.google.com/specimen/Borel).

Is there any valid reason as to why you'd actually want to `continue` in the cases where line_y < 0.0?

**Comment by jackpot51** [comment]
When scrolling is used this filters out lines with parts outside of the buffer's view.

**Comment by jackpot51** [comment]
What line height are you using? line_y is the baseline of the text.

**Comment by maxmelander** [comment]
The line height is set to 1.2. Should lines not be skipped if the bottom of the line is above the buffer view rather than the baseline? Here's what this font looks like in figma, as an example:

![image](https://github.com/pop-os/cosmic-text/assets/5417256/157eae14-d4f1-4920-a0ed-5d05b4087818)

**Comment by maxmelander** [comment]
I'll close this issue. My bad, and thanks for helping me out!:)
