### ISSUE TITLE
Editor Clone

### ISSUE THREAD

**Issue by JL710** [pop-os/cosmic-text#283]
Is there a reason why [`Editor`](https://docs.rs/cosmic-text/latest/cosmic_text/struct.Editor.html) is not Clone?

I think it would be usefull to some applications to have the ability to clone a Editor. My app for example has issues with this (can not use editor because of it).

**Comment by jackpot51** [comment]
Do you want to make a PR that makes it derive clone?

**Comment by JL710** [comment]
> Do you want to make a PR that makes it derive clone?

I am struggeling with adding Clone for `BufferRef::Borrowed`
```rs
#[derive(Debug)]
pub enum BufferRef<'buffer> {
    Owned(Buffer),
    Borrowed(&'buffer mut Buffer),
    Arc(Arc<Buffer>),
}
```

Do you have an Idea how I can make this Clone?
