### ISSUE TITLE
Shortcuts like CTRL + Backspace

### ISSUE THREAD

**Issue by Psyhackological** [pop-os/cosmic-text#299]
I know new features are planned for Epoch 2, but I will add it just to keep it in mind. For now, I'm writing about simple backspace feature like:

## Example

`|` <- cursor

```text
This is the sentence|
```

`CTRL + Backspace`

```text
This is the |
```

I think it's almost the same as doing `CTRL + w` in Terminal.

**Comment by leviport** [comment]
I believe this is a duplicate of https://github.com/pop-os/cosmic-edit/issues/208

Cosmic-edit is the text editor. Cosmic-text is the text rendering library.

**Comment by Psyhackological** [comment]
Oh, you're right @leviport, thanks for explanation. Closing then.
