### ISSUE TITLE
example `editor-libcosmic` does not properly apply scale

### ISSUE THREAD

**Issue by WhyNotHugo** [pop-os/cosmic-text#33]
Running the `editor-libcosmic` example, I get this:

![image](https://user-images.githubusercontent.com/730811/199829260-d7fe43f2-cc0f-4145-a1ec-6f86e3739f1c.png)

There is no text rendered anywhere. Clicking on the big textfield and typing does nothing. Opening a file changes nothing. The pulldown menus and toggle buttons respond, but do nothing.

**Comment by mmstick** [comment]
This looks like a graphics driver issue. What GPU do you have?

**Comment by WhyNotHugo** [comment]
Oh, that was on Asahi Linux / M1. So software rendering. I'll try on another host.

**Comment by WhyNotHugo** [comment]
I tried on Intel, text rendering is very blurry:

![image](https://user-images.githubusercontent.com/730811/199837359-c68e463e-55a3-40d3-9ccb-2e2811a93c35.png)

**Comment by WhyNotHugo** [comment]
![Screenshot from 2022-11-03 at 22_25_38 092491215](https://user-images.githubusercontent.com/730811/199837414-25d14767-779f-4020-8ea1-6d91b5e9248a.png)

**Comment by WhyNotHugo** [comment]
Dammit, github compreses too much: https://0x0.st/ogOl.09249121

**Comment by jackpot51** [comment]
You should run `cargo update` to ensure you have the latest version of iced. We have a patched version that fixes the blurriness.

**Comment by WhyNotHugo** [comment]
I think the issue is the example itself isn't handling the scale properly. This becomes extremely obvious when setting scale=6:

![image](https://user-images.githubusercontent.com/730811/205447310-3e7c68b9-e887-4d28-8425-a3ad24e99ea6.png)

I can repro this with:

```sh
cd ~/clones/github.com/pop-os/cosmic-text
cd examples/rich-text/
echo "output * scale 6\nxwayland off\nexec cargo run" > sway.conf
sway -c sway.conf
```

If you run your terminal (e.g.: `foot`) instead of `cargo run`, it renders perfectly crisp.

**Comment by VitalyAnkh** [comment]
Is this problem fixed by https://github.com/pop-os/cosmic-text/commit/d85f12af8bbee5a3ef97dc9785f8193a0c3b5f4e?

**Comment by WhyNotHugo** [comment]
Yeah, now it's nice and sharp!
