### ISSUE TITLE
Emoticon Not Rendering as Expected?

### ISSUE THREAD

**Issue by genusistimelord** [pop-os/cosmic-text#47]
So currently in my source I have

![image](https://user-images.githubusercontent.com/1034709/204704518-22a9c447-351d-4d43-bec8-5c21ba46a13a.png)

but it currently renders as 
![image](https://user-images.githubusercontent.com/1034709/204704558-4e20c37e-7fa0-4961-a88c-122aac9fc79f.png)

**Comment by hojjatabdollahi** [comment]
Can you share the string in this example?

**Comment by genusistimelord** [comment]
&format!("生活,삶,जिंदगी 😀 FPS: {}", fps),

copy pasted this exactly how it is in the source.

**Comment by hojjatabdollahi** [comment]
I can not replicate this error. If you save this string into a file and open it in `editor-libcosmic`, it looks OK.
 
<img width="255" alt="emoji" src="https://user-images.githubusercontent.com/2222199/205218661-d70ade05-51ea-4a81-8cf1-008dfc75334d.png">

**Comment by genusistimelord** [comment]
So i was debugging this and noticed something weird.

First off here is the code itself doing to offsets.

```
for run in buffer.layout_runs() {
            let line_y = run.line_y;

            for glyph in run.glyphs.iter() {
                let (allocation, is_color) = if let Some(allocation) =
                    text_atlas.atlas.get(&glyph.cache_key)
                {
                    (allocation, false)
                } else if let Some(allocation) =
                    emoji_atlas.atlas.get(&glyph.cache_key)
                {
                    (allocation, true)
                } else {
                    continue;
                };

                let (u, v, width, height) = allocation.rect();
                let (u, v, width, height) =
                    (u as i32, v as i32, width as f32, height as f32);

                let (x, y) = (
                    (pos[0] + glyph.x_int) as f32,
                    (pos[1] + line_y + glyph.y_int) as f32,
                );

                let (u1, v1) = (u as f32, v as f32);

                let color = if is_color {
                    Color::rgba(255, 255, 255, 255)
                } else {
                    match glyph.color_opt {
                        Some(color) => color,
                        None => self.color,
                    }
                };

                let default = TextVertex {
                    position: [x, y, pos[2] as f32],
                    hw: [width, height],
                    tex_coord: [u1, v1],
                    layer: allocation.layer as u32,
                    color: color.0,
                    is_color: is_color as u32,
                };

                text_buf.push(default);
            }
        }
```

Secondly When it gets too गी the width becomes 0

![image](https://user-images.githubusercontent.com/1034709/205322645-aa98025d-3009-4e25-82ac-f1d6fe5cede0.png)

I would expect this to be the size of the last glyph? Then when moved to the next glyph which apparently is the Smiley face

![image](https://user-images.githubusercontent.com/1034709/205322836-7d3aa8a4-45ff-4994-9bfb-728ffe1d9b61.png)

I will see if maybe my version is just behind using cargo update and test again but its acting strange around that part.

**Comment by genusistimelord** [comment]
this was fixed by adding the image.placement.left to the X position.
