### ISSUE TITLE
make text shaping use swash optionally

### ISSUE THREAD

**Issue by rice7th** [pop-os/cosmic-text#53]
Rustybuzz is very accurate text shaping library, but as they say in their own readme, their implementation is slower than HarfBuzz. Swash also provides high quality text shaping while being more performant than rustybuzz, though it is still a bit unstable and has some bugs.

It doesn't seem to be implemented at the moment, so why not make a feature that uses swash for shaping instead of rustybuzz?

**Comment by MarcGuiselin** [comment]
As @jackpot51 explains in https://github.com/pop-os/cosmic-text/issues/172, using swash would lead to a regression in cosmic-text's capabilities and this would not be acceptable to the goals of the project.

I suggest this issue be closed.

**Comment by notgull** [comment]
Not to mention, by using `Shaping::Basic` you can use `swash` shaping.

**Comment by rice7th** [comment]
@MarcGuiselin ok, thank you for the information. Closing this right now.
