### ISSUE TITLE
feature request: Add text justification

### ISSUE THREAD

**Issue by notgull** [pop-os/cosmic-text#76]
I am currently developing a `cosmic-text`-based implementation of the [`piet`](https://docs.rs/piet) text API, see [here](https://github.com/notgull/piet-cosmic-text). The only bits from `piet` that are currently unimplemented are variable font sizes (already raised in #64) and text justification.

`piet` expects there to be utilities for text justification, with start (default), right, center and justified alignments. See [this enum](https://docs.rs/piet/latest/piet/enum.TextAlignment.html) for more information.

Are there any plans to add text alignment to `cosmic-text`?

**Comment by grovesNL** [comment]
On the iced Discord (under discussions/Advanced Text Handling) we briefly discussed adding justification and alignment to cosmic-text's `Attrs`.

It's possible to work around it after layout has already happened by shifting glyphs around in the final layout line (I use this technique for centering text currently), but obviously that's not ideal.

**Comment by notgull** [comment]
Closed by #78

**Comment by jackpot51** [comment]
I think the system @hojjatabdollahi designed that each buffer line has alignment works best. It matches what was done for wrapping, since we cannot do spans of test inside a paragraph with different alignment as far as I know.

**Comment by jackpot51** [comment]
If there are concerns with that implementation, please open another issue.
