### ISSUE TITLE
FontSystem::new() takes a significant amount of time

### ISSUE THREAD

**Issue by notgull** [pop-os/cosmic-text#91]
On my system (Xubuntu), running `FontSystem::new()` takes a significant amount of time. On release, it takes around a second to run. On debug, it takes up to ten seconds.

There should probably be some measures taken to make sure `FontSystem` runs quickly. However, it should also be noted somewhere that `FontSystem` takes a while to load.

**Comment by jackpot51** [comment]
The major time is due to mapping every font, I believe. Lazy mapping would help a lot.

**Comment by notgull** [comment]
If the fonts aren't already in hot memory that can take a while as well. I just recorded system font loading taking 30 seconds on debug mode.

**Comment by soloturn** [comment]
is this the same as https://github.com/pop-os/cosmic-text-editor/issues/3 ?

**Comment by jackpot51** [comment]
Lazy mapping is merged, please see if this is fixed

**Comment by notgull** [comment]
Looks good to me from a glance, I'll post more in-depth statistics later

**Comment by xiaopengli89** [comment]
> Lazy mapping is merged, please see if this is fixed

@jackpot51  The `FontSystem::new` method is still slow on my computer (Apple M1 Pro).
